### ISSUE TITLE
Label Accuracy is counted by dice threshold

### ISSUE THREAD

**Issue by LeonMeon** [M3DV/RibSeg#17]
Hello!
https://github.com/M3DV/RibSeg/blob/5a0d496fbf5b081a9f0aeb16820ddb906773c197/segmentation/metrics.py#L53 -  this line means that you are using dice threshold to calculate Label Accuracy. But in the article  (https://arxiv.org/abs/2210.09309)  says that the Label Accuracy is calculated by the Recall threshold  (Section V ). Which version is correct?

**Comment by ShixuanGu** [comment]
Many thanks for pointing it out, the Recall threshold is correct, we haven't uploaded the code for RibSeg v2 yet. (which will be done soon) Sorry for the confusion!
