### ISSUE TITLE
How to use this code on ribfrac dataset for five kinds of rib segmentation

### ISSUE THREAD

**Issue by BelieferQAQ** [M3DV/RibSeg#9]
Hello, I want to change the ribseg code for the segmentation of five rib fracture types in the ribfrac data set. What are the main changes? thank you

**Comment by ShixuanGu** [comment]
Ribfrac dataset is not for segmentation task. Please refer to the RibFrac dataset paper for details. 

In this study, we only use the CT scans from RibFrac. data_prepare is to preprocess the CT scans, it has nothing to do with centerline.

**Comment by BelieferQAQ** [comment]
> 



> Ribfrac dataset is not for segmentation task. Please refer to the RibFrac dataset paper for details.
> 
> In this study, we only use the CT scans from RibFrac. data_prepare is to preprocess the CT scans, it has nothing to do with centerline.

Hello, I'm going to process the label in the ribfrac data set according to the nnunet data preprocessing method, that is, set the pixel value of 1-5 to represent five fracture types, and use 0 to represent the background. Then use the ribseg code to segment five kinds of rib fractures. Is this OK?
If possible, this statement SEG_ Classes = {'rib': [0,1]} how to change it?
Thank you very much.

**Comment by ShixuanGu** [comment]
I think it's not relevant to this repo, might I suggest reaching out to some of the advisors in your group, who I am sure will be happy to provide some suggestions on your task.

**Comment by BelieferQAQ** [comment]
> 

Thank you

**Comment by BelieferQAQ** [comment]
In addition, I would like to ask you,
This is the source code of pointnet++:
seg_ classes = {'Earphone': [16, 17, 18], 'Motorbike': [30, 31, 32, 33, 34, 35], 'Rocket': [41, 42, 43],
'Car': [8, 9, 10, 11], 'Laptop': [28, 29], 'Cap': [6, 7], 'Skateboard': [44, 45, 46], 'Mug': [36, 37],
'Guitar': [19, 20, 21], 'Bag': [4, 5], 'Lamp': [24, 25, 26, 27], 'Table': [47, 48, 49],
'Airplane': [0, 1, 2, 3], 'Pistol': [38, 39, 40], 'Chair': [12, 13, 14, 15], 'Knife': [22, 23]}
This is the code of ribseg:
seg_ classes = {'rib': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
'Earphone': [44, 45], 'Motorbike': [30, 31, 32, 33, 34, 35], 'Rocket': [41, 42, 43],
'Car': [29], 'Laptop': [28], 'Cap': [26], 'Skateboard': [46],
'Mug': [36], 'Guitar': [39, 40], 'Bag': [27], 'Lamp': [25],
'Table': [47], 'Airplane': [48], 'Pistol': [38],
'Chair': [37], 'Knife': [49]}
Why is it changed like this? Why is the rib 0-24.

**Comment by ShixuanGu** [comment]
ha, thanks for reminding, these are just poorly written codes, you could simply delete them since that's binary classification for rib seg task. I'll clean the code later.

**Comment by BelieferQAQ** [comment]
> ha, thanks for reminding, these are just poorly written codes, you could simply delete them since that's binary classification for rib seg task. I'll clean the code later.

thank you

**Comment by BelieferQAQ** [comment]
> ha, thanks for reminding, these are just poorly written codes, you could simply delete them since that's binary classification for rib seg task. I'll clean the code later.

I deleted this part of the code and will change seg_ classes = {'rib':[0,1]}，num_ classes = 1，num_ Part = 2, but the error "runtimeerror: shape'[8, 16, 1]'is invalid for input of size 8" is reported. Why is this?
In addition, excuse me
seg_ classes = {'rib': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
'Earphone': [44, 45], 'Motorbike': [30, 31, 32, 33, 34, 35], 'Rocket': [41, 42, 43],
'Car': [29], 'Laptop': [28], 'Cap': [26], 'Skateboard': [46],
'Mug': [36], 'Guitar': [39, 40], 'Bag': [27], 'Lamp': [25],
'Table': [47], 'Airplane': [48], 'Pistol': [38],
'Chair': [37], 'Knife': [49]}
What do the numbers 44, 45, 30, 31 in mean?
I'm looking forward to your answer
